// Centralized tags for case studies to ensure consistency across translations
export const caseStudyTags = {
  "basf-chemical-data-platform": [
    "Python",
    "Data Platform",
    "Azure Databricks",
    "Apache Spark",
    "Pyspark",
    "Pandas",
    "Dagster",
    "Kubernetes",
    "ArgoCD",
    "Terraform",
    "Azure",
    "DevOps",
    "CI/CD",
    "Apache Airflow",
    "Life Sciences",
  ],
  "abn-amro-data-pipeline": [
    "Python",
    "Data Platform",
    "Azure Databricks",
    "Apache Spark",
    "Pyspark",
    "Pandas",
    "Dagster",
    "Azure Data Factory",
    "Apache Airflow",
    "Kubernetes",
    "ArgoCD",
    "Terraform",
    "Apache Kafka",
    "Azure",
    "Banking",
    "DevOps",
  ],
  "minvws-healthcare-devops": [
    "Python",
    "FastAPI",
    "Pydantic",
    "C#",
    ".NET",
    "Kubernetes",
    "Azure",
    "Terraform",
    "Ansible",
    "Azure DevOps",
    "SonarQube",
    "Docker",
    "Government",
    "Healthcare",
    "Security",
    "DevOps",
  ],
  "het-veer-iot-platform": [
    "Python",
    "FastAPI",
    "Pydantic",
    "React",
    "TypeScript",
    "PostgreSQL",
    "Kubernetes",
    "Docker",
    "Jenkins",
    "Ansible",
    "Azure",
    "Manufacturing",
    "IoT",
    "Automation",
    "DevOps",
  ],
  "ns-railway-operations": [
    "Python",
    "Pandas",
    "FastAPI",
    "React",
    "TypeScript",
    "Java",
    "Docker",
    "Kubernetes",
    "ArgoCD",
    "Azure",
    "Azure DevOps",
    "SonarQube",
    "Transportation",
    "SaaS",
    "DevOps",
  ],
  "beugelbuddy-saas-platform": [
    "Python",
    "Django",
    "Flask",
    "Dagster",
    "React.js",
    "TypeScript",
    "Apache Kafka",
    "Kubernetes",
    "Docker",
    "AWS",
    "Node.js",
    "PostgreSQL",
    "Healthcare",
    "SaaS",
    "Multi-tenant",
  ],
} as const;
