import WorkListing from "./WorkListing";

const data: WorkListing[] = [
  {
    jobTitle: "Senior Software Engineer, DevOps Engineer",
    company: "Octave B.V.",
    start: new Date("2025-01-06T00:00:00"),
    tags: [
      "Python",
      "Data Science",
      "PostgreSQL",
      "Test-driven development",
      "Automatic Testing",
      "Go",
      "AWS Serverless",
      "DevOps",
      "Git",
      "Agile",
      "CI/CD",
      "Linux",
      "JIRA",
      "RBAC",
      "OAUTH2",
      "IAM",
      "Docker",
      "Kubernetes",
      "HTML",
      "CSS",
      "Containerisation",
      "AI",
      "Ansible",
      "TypeScript",
      "Node.js",
    ],
    end: new Date("2025-05-06T00:00:00"),
    description_translation_key: "octave",
  },
  {
    jobTitle: "Senior Software Engineer, DevOps Engineer",
    company: "Ministerie van Volksgezondheid, Welzijn en Sport",
    start: new Date("2024-09-09T00:00:00"),
    tags: [
      "Python",
      "C#",
      ".NET",
      "Data Science",
      "PostgreSQL",
      "Test-driven development",
      "Automatic Testing",
      "Go",
      "Azure",
      "DevOps",
      "Git",
      "Agile",
      "CI/CD",
      "SonarQube",
      "Linux",
      "BitBucket",
      "JIRA",
      "RBAC",
      "OAUTH2",
      "IAM",
      "Docker",
      "Kubernetes",
      "HTML",
      "CSS",
      "Containerisation",
      "VoIP",
      "TypeScript",
      "Node.js",
      "Ansible",
    ],
    end: new Date("2025-01-06T00:00:00"),
    description_translation_key: "minvws",
  },
  {
    jobTitle: "Senior Software Engineer, DevOps Engineer",
    company: "ABN AMRO",
    start: new Date("2023-05-01T00:00:00"),
    tags: [
      "Python",
      "Data Science",
      "PostgreSQL",
      "NoSQL",
      "Linux",
      "Test-driven development",
      "Automatic Testing",
      "Azure",
      "Dagster",
      "Threat Modeling",
      "DevOps",
      "Git",
      "Agile",
      "CI/CD",
      "SonarQube",
      "Azure DevOps",
      "Azure Cloud",
      "Azure Databricks",
      "Apache Spark",
      "Azure Functions",
      "Azure Data Factory",
      "ArgoCD",
      "BitBucket",
      "Ansible",
      "HTML",
      "CSS",
      "C#",
      ".NET",
      "JIRA",
      "RBAC",
      "OAUTH2",
      "IAM",
      "Apache Airflow",
      "Docker",
      "Kubernetes",
      "Containerisation",
      "Apache Kafka",
      "TypeScript",
      "Node.js",
    ],
    end: new Date("2024-09-09T00:00:00"),
    description_translation_key: "abnamro",
  },
  {
    jobTitle: "Senior Software Engineer, DevOps Engineer",
    company: "Het Veer",
    start: new Date("2022-11-01T00:00:00"),
    tags: [
      "Python",
      "Data Science",
      "FastAPI",
      "PostgreSQL",
      "NoSQL",
      "React",
      "HTML",
      "CSS",
      "Test-driven development",
      "Automatic Testing",
      "Linux",
      "Embedded software development",
      "Git",
      "Threat Modeling",
      "Agile",
      "CI/CD",
      "Azure DevOps",
      "Azure Cloud",
      "Jenkins",
      "TypeScript",
      "JavaScript",
      "Ansible",
      "RBAC",
      "OAUTH2",
      "IAM",
      "Docker",
      "Kubernetes",
      "Containerisation",
    ],
    end: new Date("2023-05-01T00:00:00"),
    description_translation_key: "hetveer",
  },
  {
    jobTitle: "Senior Software Engineer, DevOps Engineer",
    company: "NS",
    start: new Date("2022-06-01T00:00:00"),
    tags: [
      "Python",
      "Data Science",
      "FastAPI",
      "PostgreSQL",
      "NoSQL",
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "Test-driven development",
      "Embedded software development",
      "Linux",
      "Automatic Testing",
      "Threat Modeling",
      "RBAC",
      "OAUTH2",
      "IAM",
      "Git",
      "Agile",
      "Java",
      "CI/CD",
      "SonarQube",
      "Ansible",
      "Azure DevOps",
      "Azure Cloud",
      "Docker",
      "Kubernetes",
      "ArgoCD",
      "Containerisation",
    ],
    end: new Date("2023-11-01T00:00:00"),
    description_translation_key: "ns",
  },
  {
    jobTitle: "Head of Engineering",
    company: "Pixelsquare B.V.",
    start: new Date("2019-09-01T00:00:00"),
    tags: [
      "Python",
      "Flask",
      "Django",
      "Dagster",
      "C#",
      ".NET",
      ".NET Entity Framework",
      "Npgsql",
      "Xunit",
      "PostgreSQL",
      "Linux",
      "MySQL",
      "JavaScript",
      "TypeScript",
      "Test-driven development",
      "Langchain",
      "Automatic Testing",
      "VMWare",
      "Embedded software development",
      "React",
      "HTML",
      "CSS",
      "Vue",
      "Backstage",
      "Ansible",
      "SonarQube",
      "Java",
      "Git",
      "Agile",
      "CI/CD",
      "Azure DevOps",
      "Docker",
      "Kubernetes",
      "Containerisation",
      "Apache Kafka",
    ],
    end: null,
    description_translation_key: "pixelsquare",
  },
  {
    jobTitle: "Head of Engineering",
    company: "BeugelBuddy",
    start: new Date("2021-04-01T00:00:00"),
    tags: [
      "Python",
      "Data Science",
      "Flask",
      "Django",
      "Dagster",
      "FastAPI",
      "Node.js",
      "Elixir",
      "Test-driven development",
      "Automatic testing",
      "Linux",
      "Embedded software development",
      "Apache Kafka",
      "React.js",
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "Elastic Search",
      "Langchain",
      "Ansible",
      "Git",
      "Agile",
      "CI/CD",
      "WordPress",
      "AWS Serverless",
      "Java",
      "Azure DevOps",
      "Docker",
      "Kubernetes",
      "Containerisation",
      "Agile",
    ],
    end: null,
    description_translation_key: "beugelbuddy",
  },
  {
    jobTitle: "Full-stack developer",
    company: "ZorgSaam",
    start: new Date("2019-08-01T00:00:00"),
    tags: [
      "PHP",
      "JavaScript",
      "TypeScript",
      "React",
      "HTML",
      "CSS",
      "Test-driven development",
      "Automatic Testing",
      "PostgreSQL",
      "MySQL",
      "NoSQL",
      "WordPress",
      "Linux",
      "Git",
      "BitBucket",
      "JIRA",
      "Agile",
      "CI/CD",
      "Docker",
      "Kubernetes",
      "Containerisation",
    ],
    end: new Date("2019-09-01T00:00:00"),
    description_translation_key: "zorgsaam",
  },
  {
    jobTitle: "Trainee full-stack developer",
    company: "ZorgSaam",
    start: new Date("2018-09-01T00:00:00"),
    tags: [
      "PHP",
      "JavaScript",
      "TypeScript",
      "React",
      "HTML",
      "CSS",
      "Test-driven development",
      "Automatic Testing",
      "PostgreSQL",
      "MySQL",
      "NoSQL",
      "Linux",
      "WordPress",
      "Git",
      "Agile",
      "BitBucket",
      "JIRA",
      "CI/CD",
      "Docker",
      "Kubernetes",
      "Containerisation",
    ],
    end: new Date("2019-02-01T00:00:00"),
    description_translation_key: "zorgsaam_trainee",
  },
  {
    jobTitle: "Trainee full-stack developer",
    company: "Laveto",
    start: new Date("2017-09-01T00:00:00"),
    tags: [
      "PHP",
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "Test-driven development",
      "Automatic Testing",
      "Linux",
      "Git",
      "Agile",
      "CI/CD",
      "PostgreSQL",
      "MySQL",
      "Agile",
    ],
    end: new Date("2017-12-01T00:00:00"),
    description_translation_key: "laveto",
  },
  {
    jobTitle: "Trainee service-support employee",
    company: "Scalda",
    start: new Date("2015-10-01T00:00:00"),
    tags: [
      "Python",
      "C#",
      ".NET",
      ".NET Entity Framework",
      "Linux",
      "Npgsql",
      "PostgreSQL",
      "MySQL",
      "Node.js",
      "Test-driven development",
      "Automatic Testing",
      "JavaScript",
      "HTML",
      "CSS",
      "TypeScript",
      "VMWare",
      "Embedded software development",
      "Git",
      "Agile",
      "CI/CD",
    ],
    end: new Date("2016-06-01T00:00:00"),
    description_translation_key: "scalda",
  },
  {
    jobTitle: "Trainee 1ste servicedesk employee",
    company: "OVET B.V.",
    start: new Date("2015-04-01T00:00:00"),
    tags: [
      "IT Support",
      "Test-driven development",
      "Infrastructure Management",
      "Automatic Testing",
      "Linux",
      "VMWare",
      "Git",
      "Agile",
    ],
    end: new Date("2015-08-01T00:00:00"),
    description_translation_key: "ovet",
  },
  {
    jobTitle: "Trainee service-support employee",
    company: "Scalda",
    start: new Date("2013-10-01T00:00:00"),
    tags: [
      "Python",
      "C#",
      ".NET",
      ".NET Entity Framework",
      "Npgsql",
      "PostgreSQL",
      "MySQL",
      "Test-driven development",
      "Automatic Testing",
      "Linux",
      "JavaScript",
      "HTML",
      "CSS",
      "TypeScript",
      "VMWare",
      "Embedded software development",
      "Git",
      "Agile",
      "CI/CD",
    ],
    end: new Date("2014-08-01T00:00:00"),
    description_translation_key: "scalda_2",
  },
  {
    jobTitle: "Trainee service-support employee",
    company: "Scalda",
    start: new Date("2013-02-01T00:00:00"),
    tags: [
      "Python",
      "C#",
      ".NET",
      ".NET Entity Framework",
      "Npgsql",
      "Xunit",
      "PostgreSQL",
      "MySQL",
      "Linux",
      "JavaScript",
      "TypeScript",
      "VMWare",
      "React",
      "HTML",
      "CSS",
      "Vue",
      "Test-driven development",
      "Automatic Testing",
      "Embedded software development",
      "Git",
      "Agile",
      "CI/CD",
    ],
    end: new Date("2013-08-01T00:00:00"),
    description_translation_key: "scalda_1",
  },
];
export default data;
