import WorkListing from "./WorkListing";


const data: WorkListing[] = [
    {
        "jobTitle": "Senior Software Engineer, DevOps Engineer",
        "company": "Octave B.V.",
        "start": new Date("2025-01-06T00:00:00"),
        "tags": [
            "Python",
            "Data Science",
            "PostgreSQL",
            "Test-driven development",
            "Automatic Testing",
            "Go",
            "AWS Serverless",
            "DevOps",
            "Git",
            "Agile",
            "CI/CD",
            "Linux",
            "JIRA",
            "RBAC",
            "OAUTH2",
            "IAM",
            "Docker",
            "Kubernetes",
            "HTML",
            "CSS",
            "Containerisation",
            "AI",
            "Ansible",
            "TypeScript",
            "Node.js"
        ],
        "end": new Date("2025-05-06T00:00:00"),
        "jobDescription": "Het doorontwikkelen, beheren en ondersteunen van real-time EMS en BMS-systemen. Hierbij word voornamelijk Python en AWS verschillende services gebruikt. Tevens komen hier verschillende DevOps werkzaamheden bij kijken zoals het ontwikkelen en beheren van CI/CD pipelines. Leiding geven en begeleiden van het proces maakte ook onderdeel uit van het werk.",
    },
    {
        "jobTitle": "Senior Software Engineer, DevOps Engineer",
        "company": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "start": new Date("2024-09-09T00:00:00"),
        "tags": [
            "Python",
            "C#",
            ".NET",
            "Data Science",
            "PostgreSQL",
            "Test-driven development",
            "Automatic Testing",
            "Go",
            "Azure",
            "DevOps",
            "Git",
            "Agile",
            "CI/CD",
            "SonarQube",
            "Linux",
            "BitBucket",
            "JIRA",
            "RBAC",
            "OAUTH2",
            "IAM",
            "Docker",
            "Kubernetes",
            "HTML",
            "CSS",
            "Containerisation",
            "VoIP",
            "TypeScript",
            "Node.js",
            "Ansible"
        ],
        "end": new Date("2025-01-06T00:00:00"),
        "jobDescription": "Het ontwikkelen en beheren van verschillende applicaties binnen het iRealisatie project ter bevordering van het Nederlandse zorgstelsel. Hiervoor word voornamelijk Python gebruikt in combinatie met verschillende DevOps werkzaamheden zoals het ontwikkelen en beheren van CI/CD pipelines. Leiding geven en begeleiden van het proces maakte ook onderdeel uit van het werk.",
    },
    {
        "jobTitle": "Senior Software Engineer, DevOps Engineer",
        "company": "ABN AMRO",
        "start": new Date("2023-05-01T00:00:00"),
        "tags": [
            "Python",
            "Data Science",
            "PostgreSQL",
            "NoSQL",
            "Linux",
            "Test-driven development",
            "Automatic Testing",
            "Azure",
            "Threat Modeling",
            "DevOps",
            "Git",
            "Agile",
            "CI/CD",
            "SonarQube",
            "Azure DevOps",
            "Azure Cloud",
            "Azure Databricks",
            "Apache Spark",
            "Azure Functions",
            "Azure Data Factory",
            "ArgoCD",
            "BitBucket",
            "Ansible",
            "HTML",
            "CSS",
            "C#",
            ".NET",
            "JIRA",
            "RBAC",
            "OAUTH2",
            "IAM",
            "Apache Airflow",
            "Docker",
            "Kubernetes",
            "Containerisation",
            "Apache Kafka",
            "TypeScript",
            "Node.js"
        ],
        "end": new Date("2024-09-09T00:00:00"),
        "jobDescription": "Ontwikkelen, beheren en ondersteunen van een op maat gemaakte softwareoplossing voor grootschalige gegevensbeschikbaarheid en -transformatie. Dit omvat het gebruik van verschillende Azure-diensten zoals Databricks, Data Factory en pipelines. Daarnaast wordt er een aanzienlijke hoeveelheid DevOps-werk verricht, waaronder het ontwikkelen en beheren van CI/CD-pipelines en het onderhouden en voorbereiden van een Azure-omgeving voor productie. Leiding geven en begeleiden van het proces maakte ook onderdeel uit van het werk.",
    },
    {
        "jobTitle": "Senior Software Engineer, DevOps Engineer",
        "company": "Het Veer",
        "start": new Date("2022-11-01T00:00:00"),
        "tags": [
            "Python",
            "Data Science",
            "FastAPI",
            "PostgreSQL",
            "NoSQL",
            "React",
            "HTML",
            "CSS",
            "Test-driven development",
            "Automatic Testing",
            "Linux",
            "Embedded software development",
            "Git",
            "Threat Modeling",
            "Agile",
            "CI/CD",
            "Azure DevOps",
            "Azure Cloud",
            "Jenkins",
            "TypeScript",
            "JavaScript",
            "Ansible",
            "RBAC",
            "OAUTH2",
            "IAM",
            "Docker",
            "Kubernetes",
            "Containerisation"
        ],
        "end": new Date("2023-05-01T00:00:00"),
        "jobDescription": "Ontwikkelen en beheren van een applicatie voor real-time controle en testen van verschillende soorten middenspanningsinstallaties. Mijn focus ligt voornamelijk op Python-ontwikkeling, naast het werken met DevOps-tools zoals Git, Jenkins en verschillende Microsoft Azure-diensten. Daarnaast houd ik me bezig met front-end ontwikkeling.",
    },
    {
        "jobTitle": "Senior Software Engineer, DevOps Engineer",
        "company": "NS",
        "start": new Date("2022-06-01T00:00:00"),
        "tags": [
            "Python",
            "Data Science",
            "FastAPI",
            "PostgreSQL",
            "NoSQL",
            "React",
            "HTML",
            "CSS",
            "JavaScript",
            "TypeScript",
            "Test-driven development",
            "Embedded software development",
            "Linux",
            "Automatic Testing",
            "Threat Modeling",
            "RBAC",
            "OAUTH2",
            "IAM",
            "Git",
            "Agile",
            "Java",
            "CI/CD",
            "SonarQube",
            "Ansible",
            "Azure DevOps",
            "Azure Cloud",
            "Docker",
            "Kubernetes",
            "ArgoCD",
            "Containerisation"
        ],
        "end": new Date("2023-11-01T00:00:00"),
        "jobDescription": "Werken aan innovatieve en uitdagende softwareontwikkeling: een beslissingsondersteunende applicatie voor real-time planning van spooronderhoud. Mijn focus ligt op Python-ontwikkeling in samenwerking met verschillende Microsoft Azure-diensten.",
    },
    {
        "jobTitle": "Eigenaar, hoofd ontwikkeling",
        "company": "Pixelsquare B.V.",
        "start": new Date("2019-09-01T00:00:00"),
        "tags": [
            "Python",
            "Flask",
            "Django",
            "C#",
            ".NET",
            ".NET Entity Framework",
            "Npgsql",
            "Xunit",
            "PostgreSQL",
            "Linux",
            "MySQL",
            "JavaScript",
            "TypeScript",
            "Test-driven development",
            "Langchain",
            "Automatic Testing",
            "VMWare",
            "Embedded software development",
            "React",
            "HTML",
            "CSS",
            "Vue",
            "Backstage",
            "Ansible",
            "SonarQube",
            "Java",
            "Git",
            "Agile",
            "CI/CD",
            "Azure DevOps",
            "Docker",
            "Kubernetes",
            "Containerisation",
            "Apache Kafka"
        ],
        "end": null,
        "jobDescription": "Werken aan innovatieve en uitdagende softwareontwikkeling: een beslissingsondersteunende applicatie voor real-time planning van spooronderhoud. Mijn focus ligt op Python-ontwikkeling in samenwerking met verschillende Microsoft Azure-diensten.",
    },
    {
        "jobTitle": "Eigenaar, hoofd ontwikkeling",
        "company": "BeugelBuddy",
        "start": new Date("2021-04-01T00:00:00"),
        "tags": [
            "Python",
            "Data Science",
            "Flask",
            "Django",
            "FastAPI",
            "Node.js",
            "Elixir",
            "Test-driven development",
            "Automatic testing",
            "Linux",
            "Embedded software development",
            "Apache Kafka",
            "React.js",
            "HTML",
            "CSS",
            "JavaScript",
            "TypeScript",
            "Elastic Search",
            "Langchain",
            "Ansible",
            "Git",
            "Agile",
            "CI/CD",
            "WordPress",
            "AWS Serverless",
            "Java",
            "Azure DevOps",
            "Docker",
            "Kubernetes",
            "Containerisation",
            "Agile"
        ],
        "end": null,
        "jobDescription": "Ontwikkelen, beheren en ondersteunen van een automatiseringsoplossing in de tandheelkunde in de vorm van een softwarepakket beschikbaar op het web, smartphone of tablet. Ik werk voornamelijk met Python (voornamelijk Flask en Django), Node.js, Elixir, JavaScript en TypeScript, naast de DevOps-praktijken en -methodologieën die ik ook bij Pixelsquare gebruik. Voor de front-end werk ik met het React-framework. Hoewel ik me specialiseer in front-end ontwikkeling, ligt mijn belangrijkste focus op het bouwen van back-ends.",
    },
    {
        "jobTitle": "Full-stack developer",
        "company": "ZorgSaam",
        "start": new Date("2019-08-01T00:00:00"),
        "tags": [
            "PHP",
            "JavaScript",
            "TypeScript",
            "React",
            "HTML",
            "CSS",
            "Test-driven development",
            "Automatic Testing",
            "PostgreSQL",
            "MySQL",
            "NoSQL",
            "WordPress",
            "Linux",
            "Git",
            "BitBucket",
            "JIRA",
            "Agile",
            "CI/CD",
            "Docker",
            "Kubernetes",
            "Containerisation"
        ],
        "end": new Date("2019-09-01T00:00:00"),
        "jobDescription": "Ontwikkelen, beheren en ondersteunen van een geautomatiseerde instructiedatabase met versiebeheer die door ZorgSaam-medewerkers wordt gebruikt. Ik heb ook gewerkt met Laravel en dezelfde DevOps-praktijken en -methodologieën als tijdens mijn stage. Daarnaast heb ik gewerkt met PostgreSQL en verschillende NoSQL-databases.",
    },
    {
        "jobTitle": "Trainee full-stack developer",
        "company": "ZorgSaam",
        "start": new Date("2018-09-01T00:00:00"),
        "tags": [
            "PHP",
            "JavaScript",
            "TypeScript",
            "React",
            "HTML",
            "CSS",
            "Test-driven development",
            "Automatic Testing",
            "PostgreSQL",
            "MySQL",
            "NoSQL",
            "Linux",
            "WordPress",
            "Git",
            "Agile",
            "BitBucket",
            "JIRA",
            "CI/CD",
            "Docker",
            "Kubernetes",
            "Containerisation"
        ],
        "end": new Date("2019-02-01T00:00:00"),
        "jobDescription": "Ontwikkelen, beheren en ondersteunen van een onderwijssysteem waarbij ZorgSaam-medewerkers een vastgesteld aantal trainingen binnen een bepaalde periode moesten afronden en punten moesten verdienen. Dit proces vereiste automatisering. Ik heb Laravel, een PHP-framework, voor dit project gebruikt. Daarnaast werd MySQL gebruikt, samen met verschillende DevOps-praktijken en -methodologieën zoals Git, TDD (Test-Driven Development) en CI (Continuous Integration) tools. Dit was een van de projecten waaraan ik tijdens die periode heb gewerkt.",
    },
    {
        "jobTitle": "Trainee full-stack developer",
        "company": "Laveto",
        "start": new Date("2017-09-01T00:00:00"),
        "tags": [
            "PHP",
            "HTML",
            "CSS",
            "JavaScript",
            "TypeScript",
            "Test-driven development",
            "Automatic Testing",
            "Linux",
            "Git",
            "Agile",
            "CI/CD",
            "PostgreSQL",
            "MySQL",
            "Agile"
        ],
        "end": new Date("2017-12-01T00:00:00"),
        "jobDescription": "Ontwikkelen van een kwaliteitsmanagementsysteem om interne bedrijfsprocessen te automatiseren en te verbeteren. Dit systeem is gebouwd met Laravel, waarbij ik mijn eerdere ervaring heb benut die ik had opgedaan met een hobbyproject dat een deel van een boekhoudsysteem omvatte, voornamelijk ontwikkeld in Laravel.",
    },
    {
        "jobTitle": "Trainee service-support medewerker",
        "company": "Scalda",
        "start": new Date("2015-10-01T00:00:00"),
        "tags": [
            "Python",
            "C#",
            ".NET",
            ".NET Entity Framework",
            "Linux",
            "Npgsql",
            "PostgreSQL",
            "MySQL",
            "Node.js",
            "Test-driven development",
            "Automatic Testing",
            "JavaScript",
            "HTML",
            "CSS",
            "TypeScript",
            "VMWare",
            "Embedded software development",
            "Git",
            "Agile",
            "CI/CD"
        ],
        "end": new Date("2016-06-01T00:00:00"),
        "jobDescription": "Ondersteunen en beheren van de ICT-infrastructuur voor studenten, docenten en ander personeel op de school. Tijdens deze periode heb ik ook gewerkt aan het automatiseren van het beheer van donaties voor een goed doel, waarbij ik deze gedurende het schooljaar heb gevolgd voor verschillende inzamelingsactiviteiten. Dit project is ontwikkeld met React.js en Node.js.",
    },
    {
        "jobTitle": "Trainee 1ste servicedesk medewerker",
        "company": "OVET B.V.",
        "start": new Date("2015-04-01T00:00:00"),
        "tags": [
            "IT Support",
            "Test-driven development",
            "Infrastructure Management",
            "Automatic Testing",
            "Linux",
            "VMWare",
            "Git",
            "Agile"
        ],
        "end": new Date("2015-08-01T00:00:00"),
        "jobDescription": "Beheren van de eerste en tweede lijn servicedesk, wat inhield dat ik de ICT-infrastructuur van het bedrijf voor medewerkers onderhoudde. Daarnaast droeg ik bij aan het brainstormen en implementeren van de automatisering van verschillende bedrijfsprocessen, met behulp van een op maat gebouwd intranet voor deze doeleinden.",
    },
    {
        "jobTitle": "Trainee service-support medewerker",
        "company": "Scalda",
        "start": new Date("2013-10-01T00:00:00"),
        "tags": [
            "Python",
            "C#",
            ".NET",
            ".NET Entity Framework",
            "Npgsql",
            "PostgreSQL",
            "MySQL",
            "Test-driven development",
            "Automatic Testing",
            "Linux",
            "JavaScript",
            "HTML",
            "CSS",
            "TypeScript",
            "VMWare",
            "Embedded software development",
            "Git",
            "Agile",
            "CI/CD"
        ],
        "end": new Date("2014-08-01T00:00:00"),
        "jobDescription": "Beheren van de eerste en tweede lijn servicedesk, wat inhield dat ik de ICT-infrastructuur van het bedrijf voor medewerkers onderhoudde. Daarnaast droeg ik bij aan het brainstormen en implementeren van de automatisering van verschillende bedrijfsprocessen, met behulp van een op maat gebouwd intranet voor deze doeleinden.",
    },
    {
        "jobTitle": "Trainee service-support medewerker",
        "company": "Scalda",
        "start": new Date("2013-02-01T00:00:00"),
        "tags": [
            "Python",
            "C#",
            ".NET",
            ".NET Entity Framework",
            "Npgsql",
            "Xunit",
            "PostgreSQL",
            "MySQL",
            "Linux",
            "JavaScript",
            "TypeScript",
            "VMWare",
            "React",
            "HTML",
            "CSS",
            "Vue",
            "Test-driven development",
            "Automatic Testing",
            "Embedded software development",
            "Git",
            "Agile",
            "CI/CD"
        ],
        "end": new Date("2013-08-01T00:00:00"),
        "jobDescription": "Ondersteunen en beheren van de ICT-infrastructuur voor studenten, docenten en ander personeel op de school. Gedurende deze periode heb ik gewerkt aan het automatiseren van het uitleenproces van laptops, dat voorheen handmatig met papieren formulieren en Excel-sheets werd uitgevoerd. Deze automatisering is ontwikkeld met .NET en Python, waarbij specifieke regels die het uitleenproces reguleerden, zijn geïntegreerd.",
    }
]
export default data